//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Customer
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Customer()
    {
        this.Orders = new HashSet<Order>();
    }

    public int CID { get; set; }
    public string FName { get; set; }
    public string LName { get; set; }
    public string Phone { get; set; }
    public string Address1 { get; set; }
    public string Address2 { get; set; }
    public string Suburb { get; set; }
    public string Postcode { get; set; }
    public string State { get; set; }
    public string Ctype { get; set; }
    public string CardNo { get; set; }
    public System.DateTime ExpDate { get; set; }
    public string Email { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Order> Orders { get; set; }
}

public partial class Order
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Order()
    {
        this.Order_Products = new HashSet<Order_Products>();
    }

    public int OrderID { get; set; }
    public System.DateTime OrderDate { get; set; }
    public System.DateTime DeliveryDate { get; set; }
    public int CID { get; set; }

    public virtual Customer Customer { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Order_Products> Order_Products { get; set; }
}

public partial class Order_Products
{
    public int OrderID { get; set; }
    public int PID { get; set; }
    public int Qty { get; set; }
    public decimal TotalSale { get; set; }

    public virtual Order Order { get; set; }
    public virtual Product Product { get; set; }
}

public partial class Product
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Product()
    {
        this.Order_Products = new HashSet<Order_Products>();
    }

    public int PID { get; set; }
    public string PName { get; set; }
    public string Brand { get; set; }
    public decimal UnitPrice { get; set; }
    public int UnitsInStock { get; set; }
    public string Category { get; set; }
    public string Description { get; set; }
    public int SID { get; set; }
    public int ROL { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Order_Products> Order_Products { get; set; }
    public virtual Supplier Supplier { get; set; }
}

public partial class ShoppingCartData
{
    public int TempOrderID { get; set; }
    public int PID { get; set; }
    public string PName { get; set; }
    public decimal UnitPrice { get; set; }
    public int Quantity { get; set; }
}

public partial class Supplier
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Supplier()
    {
        this.Products = new HashSet<Product>();
    }

    public int SID { get; set; }
    public string SName { get; set; }
    public string Phone { get; set; }
    public string Email { get; set; }
    public string Address1 { get; set; }
    public string Address2 { get; set; }
    public string Suburb { get; set; }
    public string State { get; set; }
    public string Postcode { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Product> Products { get; set; }
}
